version: '3.3'
services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile

  backend:
    container_name: baidupcs-go-web
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - PASSWORD=YourPassword
    ports:
      - "8085:3001"
    volumes:
      - /root/Downloads:/downloads
